dist: xenial
language: python
python:
   - 3.7

notifications:
  email: true

before_install:
  - python setup.py install

install:
  - echo "install..."
  - pip install -r requirements.txt

script:
  - echo "script..."
  - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint
  - pytest -v -s --cov tests/
  - coverage-badge -f -o coverage.svg
  - rm .coverage
